In [1]:
import numpy as np
print(np.__version__)

2.2.2


In [3]:
## Array Cretaion
list=[10,20,30,40,50]
arr= np.array(list)
print(arr)
print('Type:', type(arr))
print('Shape', arr.shape)

[10 20 30 40 50]
Type: <class 'numpy.ndarray'>
Shape (5,)


In [7]:
arr1= np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)## rows and columns
print(arr1.size) ##length
print(arr1[0])## first row
print(arr1[0][2]) #first row 3rd column

[[1 2 3]
 [4 5 6]]
(2, 3)
6
[1 2 3]
3


In [11]:
##Genearte Array
arr1= np.zeros((2,3)) # 2X3 matrix
print(arr1)
print(arr1[0][1]) 

[[0. 0. 0.]
 [0. 0. 0.]]
0.0


In [12]:
arr2= np.ones((3,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
arr3= np.arange(1,10,3) # [1,4,7]
arr4= np.arange(2,10,3) # [2,5,8]
print(arr3+arr4) #adding [3,9,15]
print(arr3*arr4) #multiply
print(arr3**2)

[ 3  9 15]
[ 2 20 56]
[ 1 16 49]


In [17]:
sample=np.array([np.arange(1,10,3),np.arange(2,10,3)])
print(sample)

[[1 4 7]
 [2 5 8]]


In [24]:
sales=np.array([1000,1800,1500,1100,1900,1500,1950,2000,1750,1400])
#Assume 10days sales data
total_sales= np.sum(sales)
average_sales=np.average(sales)
highest_sales=np.max(sales)
lowest_sales=np.min(sales)
print('Total Sales:',total_sales)
print('Average Sales:',average_sales)
print('Highest Sale:',highest_sales)
print('Lowset Sale:',lowest_sales)

Total Sales: 15900
Average Sales: 1590.0
Highest Sale: 2000
Lowset Sale: 1000


In [25]:
print('Sales Higher than average',sales[sales>average_sales])

Sales Higher than average [1800 1900 1950 2000 1750]


In [27]:
updated= sales*1.1
print(updated)
print(sales) #original is not updated

[1100. 1980. 1650. 1210. 2090. 1650. 2145. 2200. 1925. 1540.]
[1000 1800 1500 1100 1900 1500 1950 2000 1750 1400]


In [28]:
#Sort
print(np.sort(sales))

[1000 1100 1400 1500 1500 1750 1800 1900 1950 2000]


In [29]:
import pandas as pd
df= pd.read_csv('sales_data.csv')
print(df)

   Order_ID       Product     Category  Quantity  Price  Total_Amount        Date
0      1001        Laptop  Electronics         2    700           NaN  2024-02-01
1      1002  Mobile Phone  Electronics         1    500           NaN  2024-02-02
2      1003    Headphones  Accessories         3     50           NaN  2024-02-03
3      1004         Mouse  Accessories         2     20           NaN  2024-02-04
4      1005      Keyboard  Accessories         1     30           NaN  2024-02-05
5      1006       T-shirt     Clothing         4     15           NaN  2024-02-06
6      1007        Jacket     Clothing         1     60           NaN  2024-02-07
7      1008  Refrigerator  Electronics         1    900           NaN  2024-02-08
8      1009            TV  Electronics         2   1100           NaN  2024-02-09
9      1010         Shoes     Clothing         2     40           NaN  2024-02-10


In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Order_ID      10 non-null     int64  
 1   Product       10 non-null     object 
 2   Category      10 non-null     object 
 3   Quantity      10 non-null     int64  
 4   Price         10 non-null     int64  
 5   Total_Amount  0 non-null      float64
 6   Date          10 non-null     object 
dtypes: float64(1), int64(3), object(3)
memory usage: 692.0+ bytes


In [31]:
df.isnull()

Order_ID  Product  Category  Quantity  Price  Total_Amount   Date
0     False    False     False     False  False          True  False
1     False    False     False     False  False          True  False
2     False    False     False     False  False          True  False
3     False    False     False     False  False          True  False
4     False    False     False     False  False          True  False
5     False    False     False     False  False          True  False
6     False    False     False     False  False          True  False
7     False    False     False     False  False          True  False
8     False    False     False     False  False          True  False
9     False    False     False     False  False          True  False

In [32]:
df.isna()

Order_ID  Product  Category  Quantity  Price  Total_Amount   Date
0     False    False     False     False  False          True  False
1     False    False     False     False  False          True  False
2     False    False     False     False  False          True  False
3     False    False     False     False  False          True  False
4     False    False     False     False  False          True  False
5     False    False     False     False  False          True  False
6     False    False     False     False  False          True  False
7     False    False     False     False  False          True  False
8     False    False     False     False  False          True  False
9     False    False     False     False  False          True  False

In [33]:
df.fillna(0) ##handling missing values

Order_ID       Product     Category  Quantity  Price  Total_Amount        Date
0      1001        Laptop  Electronics         2    700           0.0  2024-02-01
1      1002  Mobile Phone  Electronics         1    500           0.0  2024-02-02
2      1003    Headphones  Accessories         3     50           0.0  2024-02-03
3      1004         Mouse  Accessories         2     20           0.0  2024-02-04
4      1005      Keyboard  Accessories         1     30           0.0  2024-02-05
5      1006       T-shirt     Clothing         4     15           0.0  2024-02-06
6      1007        Jacket     Clothing         1     60           0.0  2024-02-07
7      1008  Refrigerator  Electronics         1    900           0.0  2024-02-08
8      1009            TV  Electronics         2   1100           0.0  2024-02-09
9      1010         Shoes     Clothing         2     40           0.0  2024-02-10

In [34]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [35]:
df.dtypes

Order_ID          int64
Product          object
Category         object
Quantity          int64
Price             int64
Total_Amount    float64
Date             object
dtype: object

In [38]:
df['Date']=pd.to_datetime(df['Date'])

In [39]:
df.dtypes

Order_ID                 int64
Product                 object
Category                object
Quantity                 int64
Price                    int64
Total_Amount           float64
Date            datetime64[ns]
dtype: object

In [40]:
type("hello world")

str

In [54]:
df['Quantity']= df['Quantity'].astype(int) # convert to int
df.dtypes
#for string,list,dictionary,tuple it is taking object data type only so no need to convert

Order_ID                 int64
Product                 object
Category                object
Quantity                 int64
Price                    int64
Total_Amount           float64
Date            datetime64[ns]
dtype: object